---
title: Show and Tell
labels: ["showcase"]
---

## What did you build?
Describe what you've created with VeriMeZK

## Share
- Screenshots
- Code snippets
- Links
- Demo

## Learnings
What did you learn? Any tips for others?

